name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo  # Алтернатива: git clone
          uses: actions/checkout@v4  # Используется для клонирования репозитория

        - name: Build and push image
          run: docker build --name Landing .
          timeout-minutes: 10